server:
  # 默认端口：8718
  port: 8101
  servlet:
    session:
      cookie:
        name: sentinel_dashboard_cookie
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${NACOS_HOST:twelvet-nacos}:${NACOS_PORT:8848}
        namespace: @nacos.namespace@
  mvc:
    pathmatch:
      # 在高级版本中需要兼容路径，否则404
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    org:
      springframework:
        web: info
  file:
    name: ${user.home}/logs/csp/sentinel-dashboard.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

auth:
  username: sentinel
  password: sentinel
  filter:
    exclude-urls: /,/auth/login,/auth/logout,/registry/machine,/version,/actuator/**,/details
    exclude-url-suffixes: htm,html,js,css,map,ico,ttf,woff,png

sentinel:
  dashboard:
    version: @project.version@
