server:
  port: 8888

spring:
  application:
    # 应用名称
    name: @artifactId@
  profiles:
    # 环境配置
    active: @active@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        # 解决获取IP为内网，一般微服务采用内网安全性、可用性高
        # ip: 127.0.0.1
        # 服务注册地址
        server-addr: ${NACOS_HOST:twelvet-nacos}:${NACOS_PORT:8848}
        # 命名空间
        namespace: @nacos.namespace@
      config:
        # 配置中心地址
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        # 配置文件格式
        file-extension: yml
        # 命名空间
        namespace: @nacos.namespace@
        # 配置组
        group: DEFAULT_GROUP
        # 共享配置
        # shared-configs:
          # - data-id: twelvet-app-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
    # 暂时修复因sentinel导致的无法启动
    # openfeign:
      # lazy-attributes-resolution: true
  config:
    import:
      - optional:nacos:twelvet-app-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}


  # 接入第三方OAuth2登录（开发功能-dev）
#  security:
#    oauth2:
#      client:
#        # 注册第三方客户端
#        registration:
#          gitee:
#            # 关联OAuth2 Server
#            provider: gitee
#            client-id: 305079
#            client-secret: 77ca2
#            # 授权类型
#            authorization-grant-type: authorization_code
#            # 授权范围
#            scope: user_info
#            # 回调地址
#            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
#            client-name: gitee
#          github:
#            # 关联OAuth2 Server
#            provider: github
#            client-id: ffc6b9
#            client-secret: 7d00bc26
#            # 授权类型
#            authorization-grant-type: authorization_code
#            # 授权范围
#            scope: user_info
#            # 回调地址
#            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
#            client-name: github
#        # 第三方信息换取配置(默认Google、GitHub、Facebook 和 Okta内置)
#        provider:
#          gitee:
#            # 登录地址
#            authorization-uri: https://gitee.com/oauth/authorize
#            # 换取token
#            token-uri: https://gitee.com/oauth/token
#            # 取得的user详情中的属性id的值作为Client的已认证的用户的用户名
#            user-name-attribute: id
#            # 获取用户信息
#            user-info-uri: https://gitee.com/api/v5/user
