name: test

on:
  workflow_dispatch:
  push:
    branches: [ master, jdk8 ]
  pull_request:
    branches: [ master, jdk8 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17, 21 ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: zulu
          cache: maven

      - name: mvn clean install twelvet
        run: |
          cd ./twelvet && mvn clean install

      - name: mvn spring-javaformat:validate
        run: |
          cd ./twelvet && mvn spring-javaformat:validate
          cd ../twelvet-auth && mvn spring-javaformat:validate
          cd ../twelvet-gateway && mvn spring-javaformat:validate
          cd ../twelvet-nacos && mvn spring-javaformat:validate
          cd ../twelvet-server/twelvet-server-dfs && mvn spring-javaformat:validate
          cd ../twelvet-server/twelvet-server-gen && mvn spring-javaformat:validate
          cd ../twelvet-server/twelvet-server-job && mvn spring-javaformat:validate
          cd ../twelvet-server/twelvet-server-system && mvn spring-javaformat:validate
          cd ../twelvet-visual/twelvet-visual-monitor && mvn spring-javaformat:validate
          cd ../twelvet-visual/twelvet-visual-sentinel && mvn spring-javaformat:validate

      - name: mvn clean install twelvet-auth
        run: |
          cd ./twelvet-auth && mvn clean install

      - name: mvn clean install twelvet-gateway
        run: |
          cd ./twelvet-gateway && mvn clean install

      - name: mvn clean install twelvet-server-system
        run: |
          cd ./twelvet-server/twelvet-server-system && mvn clean install

      - name: init
        run: cd docker && chmod 751 ./deploy.sh && ./deploy.sh init

      - name: Start Base
        run: |
          cd docker
          docker network create twelvet-network
          docker compose up -d twelvet-mysql twelvet-redis
          sleep 60
          docker compose up -d twelvet-nacos

      - name: Start Server
        run: |
          sleep 30
          cd docker
          docker compose up -d twelvet-gateway twelvet-auth twelvet-server-system

      - name: Check Server twelvet-mysql
        run: |
          docker logs --tail 500 twelvet-mysql

      - name: Check Server twelvet-redis
        run: |
          docker logs --tail 500 twelvet-redis

      - name: Check Server twelvet-nacos
        run: |
          docker logs --tail 500 twelvet-nacos

      - name: Check Server twelvet-gateway
        run: |
          docker logs --tail 500 twelvet-gateway

      - name: Check Server twelvet-auth
        run: |
          docker logs --tail 500 twelvet-auth

      - name: Check Server twelvet-server-system
        run: |
          docker logs --tail 500 twelvet-server-system
